### ISSUE TITLE
Change Bard Url (Now Gemini)

### ISSUE THREAD

**Issue by Luca-Pulina** [Cyfrin/evm-wallet-and-post-deployment-course#2]
Since Bard became Gemini, the path to bard.com redirects to gemini.com. A fix can prevent future` 404 Not Found` errors

**Comment by cromewar** [comment]
Hello @Luca-Pulina, Can you send a pull request for this? I will make sure this gets merged.

**Comment by Luca-Pulina** [comment]
sent

https://github.com/Cyfrin/evm-wallet-and-post-deployment-course/pull/3

**Comment by cromewar** [comment]
Amazing, thanks. The PR was merged
